/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import metodos.propietariosMysql;
import principales.propietarios;

/**
 *
 * @author user
 */
public class Liquidacion extends javax.swing.JFrame {

    ArrayList<propietarios> propietario;
    propietariosMysql dbPropietario = new propietariosMysql();

    /**
     * Creates new form Nuevo_Propietario
     */
    public Liquidacion() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("TRANSPORTES RM DEL CARIBE S.A.S - LIQUIDACION");
    }

    public void limpiar() {
        /*
        txtIdentificacion.setText("");
        txtNombrePropietario.setText("");
        txtDepartamento.setText("");
        txtMunicipio.setText("");
        txtDireccion.setText("");
        txtEmail.setText("");
        txtTelefono.setText("");
        txtIdentificacion.requestFocus();
        */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lblNit1 = new javax.swing.JLabel();
        txtFechaIngreso = new com.toedter.calendar.JDateChooser();
        lblNit8 = new javax.swing.JLabel();
        txtFechaIngreso3 = new com.toedter.calendar.JDateChooser();
        jPanel5 = new javax.swing.JPanel();
        txtIdentificacion2 = new javax.swing.JTextField();
        lblNit3 = new javax.swing.JLabel();
        txtIdentificacion4 = new javax.swing.JTextField();
        lblNit9 = new javax.swing.JLabel();
        txtIdentificacion11 = new javax.swing.JTextField();
        lblNit12 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        txtIdentificacion3 = new javax.swing.JTextField();
        lblNit4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lblNit7 = new javax.swing.JLabel();
        txtFechaIngreso2 = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblNit6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        lblNit10 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        txtIdentificacion7 = new javax.swing.JTextField();
        lblNit5 = new javax.swing.JLabel();
        txtIdentificacion8 = new javax.swing.JTextField();
        txtIdentificacion9 = new javax.swing.JTextField();
        txtIdentificacion10 = new javax.swing.JTextField();
        lblNit11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("LIQUIDACION");
        jLabel2.setFocusCycleRoot(true);
        jPanel3.add(jLabel2);
        jLabel2.setBounds(280, 6, 287, 42);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 153, 153));
        jPanel3.add(jSeparator1);
        jSeparator1.setBounds(9, 56, 830, 10);

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText(". . .");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(220, 730, 190, 40);

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel4.setLayout(null);

        lblNit1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNit1.setForeground(new java.awt.Color(255, 255, 255));
        lblNit1.setText("FECHA INICIO");
        jPanel4.add(lblNit1);
        lblNit1.setBounds(20, 10, 90, 14);

        txtFechaIngreso.setDateFormatString("yyyy-MM-dd");
        jPanel4.add(txtFechaIngreso);
        txtFechaIngreso.setBounds(20, 30, 270, 30);

        lblNit8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNit8.setForeground(new java.awt.Color(255, 255, 255));
        lblNit8.setText("FECHA FINAL");
        jPanel4.add(lblNit8);
        lblNit8.setBounds(20, 70, 90, 14);

        txtFechaIngreso3.setDateFormatString("yyyy-MM-dd");
        jPanel4.add(txtFechaIngreso3);
        txtFechaIngreso3.setBounds(20, 90, 270, 30);

        jPanel3.add(jPanel4);
        jPanel4.setBounds(520, 150, 310, 130);

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        jPanel5.setLayout(null);
        jPanel5.add(txtIdentificacion2);
        txtIdentificacion2.setBounds(10, 10, 140, 30);

        lblNit3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNit3.setForeground(new java.awt.Color(0, 51, 102));
        lblNit3.setText("SUB-TOTAL");
        jPanel5.add(lblNit3);
        lblNit3.setBounds(160, 10, 80, 14);
        jPanel5.add(txtIdentificacion4);
        txtIdentificacion4.setBounds(10, 50, 140, 30);

        lblNit9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNit9.setForeground(new java.awt.Color(0, 51, 102));
        lblNit9.setText("DESCUENTOS");
        jPanel5.add(lblNit9);
        lblNit9.setBounds(160, 50, 80, 14);
        jPanel5.add(txtIdentificacion11);
        txtIdentificacion11.setBounds(10, 90, 140, 30);

        lblNit12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNit12.setForeground(new java.awt.Color(0, 51, 102));
        lblNit12.setText("GRAN TOTAL");
        jPanel5.add(lblNit12);
        lblNit12.setBounds(160, 90, 80, 14);

        jPanel3.add(jPanel5);
        jPanel5.setBounds(540, 540, 250, 130);

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        jPanel6.setLayout(null);
        jPanel6.add(txtIdentificacion3);
        txtIdentificacion3.setBounds(20, 30, 440, 30);

        lblNit4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNit4.setForeground(new java.awt.Color(0, 51, 102));
        lblNit4.setText("TITULO DE LA LIQUIDACION");
        jPanel6.add(lblNit4);
        lblNit4.setBounds(20, 10, 180, 14);

        jPanel3.add(jPanel6);
        jPanel6.setBounds(20, 70, 480, 70);

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        jPanel7.setLayout(null);

        lblNit7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNit7.setForeground(new java.awt.Color(0, 51, 102));
        lblNit7.setText("FECHA DE LIQUIDACION");
        jPanel7.add(lblNit7);
        lblNit7.setBounds(20, 10, 150, 14);

        txtFechaIngreso2.setDateFormatString("yyyy-MM-dd");
        jPanel7.add(txtFechaIngreso2);
        txtFechaIngreso2.setBounds(20, 30, 270, 30);

        jPanel3.add(jPanel7);
        jPanel7.setBounds(520, 70, 310, 70);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_DESC", "FECHA", "DESCRIPCION", "UNIDAD", "PRECIO", "TOTAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(20, 540, 470, 180);

        lblNit6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNit6.setForeground(new java.awt.Color(0, 51, 102));
        lblNit6.setText("DESCUENTOS");
        jPanel3.add(lblNit6);
        lblNit6.setBounds(20, 520, 140, 20);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_VIAJE", "FECHA", "DIA", "RECORRIDO", "UNIDAD", "VALOR M3", "M3", "KM RECORRIDO", "TOTAL", "ID_VEHICULO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane2.setViewportView(jTable2);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(20, 300, 810, 220);

        lblNit10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNit10.setForeground(new java.awt.Color(0, 51, 102));
        lblNit10.setText("VIAJES");
        jPanel3.add(lblNit10);
        lblNit10.setBounds(20, 280, 120, 20);

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        jPanel8.setLayout(null);
        jPanel8.add(txtIdentificacion7);
        txtIdentificacion7.setBounds(20, 30, 310, 30);

        lblNit5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNit5.setForeground(new java.awt.Color(0, 51, 102));
        lblNit5.setText("CONDUCTOR");
        jPanel8.add(lblNit5);
        lblNit5.setBounds(20, 10, 100, 14);
        jPanel8.add(txtIdentificacion8);
        txtIdentificacion8.setBounds(20, 90, 310, 30);
        jPanel8.add(txtIdentificacion9);
        txtIdentificacion9.setBounds(400, 90, 70, 30);
        jPanel8.add(txtIdentificacion10);
        txtIdentificacion10.setBounds(400, 30, 70, 30);

        lblNit11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNit11.setForeground(new java.awt.Color(0, 51, 102));
        lblNit11.setText("PLACA");
        jPanel8.add(lblNit11);
        lblNit11.setBounds(20, 70, 100, 14);

        jPanel3.add(jPanel8);
        jPanel8.setBounds(20, 150, 480, 130);

        jButton2.setBackground(new java.awt.Color(0, 51, 102));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("LIQUIDAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(540, 680, 250, 40);

        jButton3.setBackground(new java.awt.Color(0, 153, 153));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("EDITAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(20, 730, 190, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 849, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 782, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        /*
        if (txtIdentificacion.getText().isEmpty() || txtNombrePropietario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe gestionar el formulario");
        } else {
            try {
                propietarios pro = new propietarios();
                pro.setIdentificacion(txtIdentificacion.getText().toUpperCase());
                pro.setNombre_propietario(txtNombrePropietario.getText().toUpperCase());
                pro.setDepartamento(txtDepartamento.getText().toUpperCase());
                pro.setMunicipio(txtMunicipio.getText().toUpperCase());
                pro.setDireccion(txtDireccion.getText().toUpperCase());

                String formato = txtFechaIngreso.getDateFormatString();
                Date date = txtFechaIngreso.getDate();
                SimpleDateFormat sdf = new SimpleDateFormat(formato);
                String dato = String.valueOf(sdf.format(date));
                pro.setFecha_ingreso(dato);

                pro.setEmail(txtEmail.getText().toUpperCase());
                pro.setTelefono(txtTelefono.getText().toUpperCase());
                pro.setEstado("ACTIVO");

                dbPropietario.insertarPropietario(pro);

                Tabla_Propietarios obj = new Tabla_Propietarios();
                obj.setVisible(true);
                dispose();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
        */

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Liquidacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Liquidacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Liquidacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Liquidacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Liquidacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblNit1;
    private javax.swing.JLabel lblNit10;
    private javax.swing.JLabel lblNit11;
    private javax.swing.JLabel lblNit12;
    private javax.swing.JLabel lblNit3;
    private javax.swing.JLabel lblNit4;
    private javax.swing.JLabel lblNit5;
    private javax.swing.JLabel lblNit6;
    private javax.swing.JLabel lblNit7;
    private javax.swing.JLabel lblNit8;
    private javax.swing.JLabel lblNit9;
    private com.toedter.calendar.JDateChooser txtFechaIngreso;
    private com.toedter.calendar.JDateChooser txtFechaIngreso2;
    private com.toedter.calendar.JDateChooser txtFechaIngreso3;
    private javax.swing.JTextField txtIdentificacion10;
    private javax.swing.JTextField txtIdentificacion11;
    private javax.swing.JTextField txtIdentificacion2;
    private javax.swing.JTextField txtIdentificacion3;
    private javax.swing.JTextField txtIdentificacion4;
    private javax.swing.JTextField txtIdentificacion7;
    private javax.swing.JTextField txtIdentificacion8;
    private javax.swing.JTextField txtIdentificacion9;
    // End of variables declaration//GEN-END:variables
}
