/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import com.mxrck.autocompleter.TextAutoCompleter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import metodos.propietariosMysql;
import metodos.viajesMysql;
import principales.conductores;
import principales.propietarios;
import principales.viajes;

/**
 *
 * @author user
 */
public final class Nuevo_Viaje extends javax.swing.JFrame {

    ArrayList<viajes> viaje;
    viajesMysql dbviaje = new viajesMysql();

    /**
     * Creates new form Nuevo_Propietario
     */
    public Nuevo_Viaje() {
        initComponents();
        this.setLocationRelativeTo(null);
        //this.setResizable(false);
        this.setTitle("TRANSPORTES RM DEL CARIBE S.A.S - NUEVO VIAJE");
        txtIdVehiculo.setEnabled(false);
        txtTotal.setEnabled(false);
        autoCompletePlaca();
        autoCompleteRecorridos();
        EnCero();
        //txtTotal.setDisabledTextColor(java.awt.Color.GREEN);
    }

    public void EnCero() {

        txtUnidad.setText("" + 1);
        //cmbValorM3.getSelectedItem().toString());
        txtM3.setText("" + 1);
        txtKm.setText("" + 1);

    }

    public void total() {

        int unidad = Integer.parseInt(txtUnidad.getText());
        int valor_m3 = Integer.parseInt(cmbValorM3.getSelectedItem().toString());
        int m3 = Integer.parseInt(txtM3.getText());
        int km = Integer.parseInt(txtKm.getText());
        int total = unidad * valor_m3 * m3 * km;

        txtTotal.setDisabledTextColor(java.awt.Color.GREEN);
        //txtTotal.setText("" + total);

    }

    public void autoCompletePlaca() {
        TextAutoCompleter TextAutoCompleter = new TextAutoCompleter(txtPlaca);
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/transporterm", "root", "Colombia_16");
            Statement st = (Statement) cn.createStatement();
            ResultSet rs = st.executeQuery("SELECT placa FROM vehiculos");
            while (rs.next()) {
                TextAutoCompleter.addItem(rs.getString("placa"));
            }
            cn.close();
        } catch (Exception e) {
            System.out.println("error: " + e);
        }
    }

    public void autoCompleteRecorridos() {
        TextAutoCompleter TextAutoCompleter = new TextAutoCompleter(txtRecorrido);
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/transporterm", "root", "Colombia_16");
            Statement st = (Statement) cn.createStatement();
            ResultSet rs = st.executeQuery("SELECT recorrido FROM recorridos");
            while (rs.next()) {
                TextAutoCompleter.addItem(rs.getString("recorrido"));
            }
            cn.close();
        } catch (Exception e) {
            System.out.println("error: " + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        txtPlaca = new javax.swing.JTextField();
        lblNit = new javax.swing.JLabel();
        lblNit3 = new javax.swing.JLabel();
        txtRecorrido = new javax.swing.JTextField();
        txtFecha = new com.toedter.calendar.JDateChooser();
        jButton2 = new javax.swing.JButton();
        lblNit2 = new javax.swing.JLabel();
        lblNit4 = new javax.swing.JLabel();
        lblNit5 = new javax.swing.JLabel();
        lblNit6 = new javax.swing.JLabel();
        txtUnidad = new javax.swing.JTextField();
        cmbValorM3 = new javax.swing.JComboBox<>();
        txtM3 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        txtTotal = new javax.swing.JTextField();
        lblNit1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        lblNit7 = new javax.swing.JLabel();
        cmbDia = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        lblNit8 = new javax.swing.JLabel();
        txtKm = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        txtIdVehiculo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(0, 102, 153));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("VIAJES");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);
        jPanel2.add(txtPlaca);
        txtPlaca.setBounds(20, 40, 170, 30);

        lblNit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNit.setText("PLACA VEHICULO");
        jPanel2.add(lblNit);
        lblNit.setBounds(20, 20, 110, 14);

        lblNit3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNit3.setText("VALOR M3");
        jPanel2.add(lblNit3);
        lblNit3.setBounds(180, 140, 80, 14);
        jPanel2.add(txtRecorrido);
        txtRecorrido.setBounds(20, 100, 300, 30);

        txtFecha.setDateFormatString("yyyy-MM-dd");
        jPanel2.add(txtFecha);
        txtFecha.setBounds(200, 40, 120, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(120, 20, 70, 20);

        lblNit2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNit2.setText("DIA");
        jPanel2.add(lblNit2);
        lblNit2.setBounds(330, 20, 60, 14);

        lblNit4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNit4.setText("KM RECORRIDOS");
        jPanel2.add(lblNit4);
        lblNit4.setBounds(330, 80, 110, 14);

        lblNit5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNit5.setText("UNIDAD");
        jPanel2.add(lblNit5);
        lblNit5.setBounds(20, 140, 60, 14);

        lblNit6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNit6.setText("M3");
        jPanel2.add(lblNit6);
        lblNit6.setBounds(330, 140, 70, 14);

        txtUnidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUnidadKeyReleased(evt);
            }
        });
        jPanel2.add(txtUnidad);
        txtUnidad.setBounds(20, 160, 130, 30);

        cmbValorM3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "400", "390" }));
        cmbValorM3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbValorM3ActionPerformed(evt);
            }
        });
        jPanel2.add(cmbValorM3);
        cmbValorM3.setBounds(180, 160, 120, 30);

        txtM3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtM3KeyReleased(evt);
            }
        });
        jPanel2.add(txtM3);
        txtM3.setBounds(330, 160, 120, 30);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);

        txtTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTotal.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });
        txtTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTotalKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTotalKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTotalKeyTyped(evt);
            }
        });
        jPanel1.add(txtTotal);
        txtTotal.setBounds(10, 10, 170, 40);

        jPanel2.add(jPanel1);
        jPanel1.setBounds(20, 210, 190, 60);

        lblNit1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNit1.setText("TOTAL");
        jPanel2.add(lblNit1);
        lblNit1.setBounds(220, 250, 50, 20);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator2);
        jSeparator2.setBounds(280, 200, 10, 70);
        jPanel2.add(jSeparator3);
        jSeparator3.setBounds(20, 200, 430, 2);

        lblNit7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNit7.setText("FECHA");
        jPanel2.add(lblNit7);
        lblNit7.setBounds(200, 20, 60, 14);

        cmbDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LUNES", "MARTES", "MIERCOLES", "JUEVES", "VIERNES", "SABADO", "DOMINGO" }));
        jPanel2.add(cmbDia);
        cmbDia.setBounds(330, 40, 120, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("REGISTRAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(300, 210, 150, 50);

        lblNit8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNit8.setText("RECORRIDO");
        jPanel2.add(lblNit8);
        lblNit8.setBounds(20, 80, 80, 14);

        txtKm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtKmKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtKmKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtKmKeyTyped(evt);
            }
        });
        jPanel2.add(txtKm);
        txtKm.setBounds(330, 100, 120, 30);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton3.setText("Buscar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(250, 80, 70, 20);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 28, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIdVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIdVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (txtIdVehiculo.getText().isEmpty() || txtTotal.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe gestionar el formulario");
        } else {
            try {
                viajes vi = new viajes();
                vi.setId_vehiculo(Integer.parseInt(txtIdVehiculo.getText()));

                String formato = txtFecha.getDateFormatString();
                Date date = txtFecha.getDate();
                SimpleDateFormat sdf = new SimpleDateFormat(formato);
                String dato = String.valueOf(sdf.format(date));
                vi.setFecha(dato);

                vi.setDia(cmbDia.getSelectedItem().toString());
                vi.setRecorrido(txtRecorrido.getText().toUpperCase());
                vi.setKm(Integer.parseInt(txtKm.getText()));
                vi.setUnidad(Integer.parseInt(txtUnidad.getText().toUpperCase()));
                vi.setValor_m3(Integer.parseInt(cmbValorM3.getSelectedItem().toString()));
                vi.setM3(Integer.parseInt(txtM3.getText()));
                vi.setTotal(Integer.parseInt(txtTotal.getText()));

                dbviaje.insertarViaje(vi);

                
                Tabla_Viajes obj = new Tabla_Viajes();
                obj.setVisible(true);
                dispose();
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        try {
            String guardar = txtPlaca.getText();
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/transporterm", "root", "Colombia_16");
            Statement st = cn.createStatement();
            PreparedStatement pst = cn.prepareStatement("Select id_vehiculo from vehiculos where placa = ?");
            pst.setString(1, guardar);
            //pst.setString(1, CMBID.getName());
            ResultSet rs = pst.executeQuery();
            //txtConductor.setText("");
            if (rs.next()) {

                viajes vi = new viajes();
                vi.setId_vehiculo(rs.getInt("id_vehiculo"));
                //txtIdConductor.setText(""+con);
                txtIdVehiculo.setText(rs.getString("id_vehiculo").trim());
                //autoCompleteConductor();
            } else {
                JOptionPane.showMessageDialog(null, "No existe el vehiculo");
            }
            cn.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "error\n" + ex.getMessage());
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        try {
            String guardar = txtRecorrido.getText();
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/transporterm", "root", "Colombia_16");
            Statement st = cn.createStatement();
            PreparedStatement pst = cn.prepareStatement("Select km_recorridos from recorridos where recorrido = ?");
            pst.setString(1, guardar);
            //pst.setString(1, CMBID.getName());
            ResultSet rs = pst.executeQuery();
            //txtConductor.setText("");
            if (rs.next()) {

                viajes vi = new viajes();
                vi.setKm(rs.getInt("km_recorridos"));
                //txtIdConductor.setText(""+con);
                txtKm.setText(rs.getString("km_recorridos").trim());

                String dato = txtKm.getText();

                if (dato.equals("") == false && dato.matches("[0-9]*")) {
                    int km = Integer.parseInt(dato);

                    int unidad = Integer.parseInt(txtUnidad.getText());
                    int valor_m3 = Integer.parseInt(cmbValorM3.getSelectedItem().toString());
                    int m3 = Integer.parseInt(txtM3.getText());
                    //int km = Integer.parseInt(txtKm.getText());
                    int total = unidad * valor_m3 * m3 * km;
                    txtTotal.setDisabledTextColor(java.awt.Color.BLUE);
                    txtTotal.setText("" + total);
                }

                //autoCompleteConductor();
            } else {
                JOptionPane.showMessageDialog(null, "No existe el recorrido");
            }
            cn.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "error\n" + ex.getMessage());
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed

        // total();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void txtTotalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTotalKeyPressed

        //total();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalKeyPressed

    private void txtTotalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTotalKeyReleased

        //total();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalKeyReleased

    private void txtTotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTotalKeyTyped

        total();

        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalKeyTyped

    private void txtKmKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKmKeyReleased

        String dato = txtKm.getText();

        if (dato.equals("") == false && dato.matches("[0-9]*")) {
            int km = Integer.parseInt(dato);

            int unidad = Integer.parseInt(txtUnidad.getText());
            int valor_m3 = Integer.parseInt(cmbValorM3.getSelectedItem().toString());
            int m3 = Integer.parseInt(txtM3.getText());
            //int km = Integer.parseInt(txtKm.getText());
            int total = unidad * valor_m3 * m3 * km;
            txtTotal.setDisabledTextColor(java.awt.Color.BLUE);
            txtTotal.setText("" + total);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_txtKmKeyReleased

    private void txtUnidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUnidadKeyReleased

        String dato = txtUnidad.getText();

        if (dato.equals("") == false && dato.matches("[0-9]*")) {
            int unidad = Integer.parseInt(dato);

            //int unidad = Integer.parseInt(txtUnidad.getText());
            int valor_m3 = Integer.parseInt(cmbValorM3.getSelectedItem().toString());
            int m3 = Integer.parseInt(txtM3.getText());
            int km = Integer.parseInt(txtKm.getText());
            int total = unidad * valor_m3 * m3 * km;
            txtTotal.setDisabledTextColor(java.awt.Color.BLUE);
            txtTotal.setText("" + total);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnidadKeyReleased

    private void txtM3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtM3KeyReleased

        String dato = txtM3.getText();

        if (dato.equals("") == false && dato.matches("[0-9]*")) {
            int m3 = Integer.parseInt(dato);

            int unidad = Integer.parseInt(txtUnidad.getText());
            int valor_m3 = Integer.parseInt(cmbValorM3.getSelectedItem().toString());
            //int m3 = Integer.parseInt(txtM3.getText());
            int km = Integer.parseInt(txtKm.getText());
            int total = unidad * valor_m3 * m3 * km;
            txtTotal.setDisabledTextColor(java.awt.Color.BLUE);
            txtTotal.setText("" + total);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_txtM3KeyReleased

    private void txtKmKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKmKeyTyped

        // TODO add your handling code here:
    }//GEN-LAST:event_txtKmKeyTyped

    private void txtKmKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKmKeyPressed

        // TODO add your handling code here:
    }//GEN-LAST:event_txtKmKeyPressed

    private void cmbValorM3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbValorM3ActionPerformed

        String dato = cmbValorM3.getSelectedItem().toString();

        if (dato.equals("") == false && dato.matches("[0-9]*")) {
            int valor_m3 = Integer.parseInt(dato);

            int unidad = Integer.parseInt(txtUnidad.getText());
            //int valor_m3 = Integer.parseInt(cmbValorM3.getSelectedItem().toString());
            int m3 = Integer.parseInt(txtM3.getText());
            int km = Integer.parseInt(txtKm.getText());
            int total = unidad * valor_m3 * m3 * km;
            txtTotal.setDisabledTextColor(java.awt.Color.BLUE);
            txtTotal.setText("" + total);
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbValorM3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nuevo_Viaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nuevo_Viaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nuevo_Viaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nuevo_Viaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nuevo_Viaje().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbDia;
    private javax.swing.JComboBox<String> cmbValorM3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblNit;
    private javax.swing.JLabel lblNit1;
    private javax.swing.JLabel lblNit2;
    private javax.swing.JLabel lblNit3;
    private javax.swing.JLabel lblNit4;
    private javax.swing.JLabel lblNit5;
    private javax.swing.JLabel lblNit6;
    private javax.swing.JLabel lblNit7;
    private javax.swing.JLabel lblNit8;
    private com.toedter.calendar.JDateChooser txtFecha;
    private javax.swing.JTextField txtIdVehiculo;
    private javax.swing.JTextField txtKm;
    private javax.swing.JTextField txtM3;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtRecorrido;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtUnidad;
    // End of variables declaration//GEN-END:variables
}
