/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import metodos.recorridosMysql;
import principales.recorridos;

/**
 *
 * @author user
 */
public class Recorridos extends javax.swing.JFrame {

    //DefaultTableModel model;
    
    ArrayList<recorridos> recorrido;
    recorridosMysql dbRecorridos = new recorridosMysql();
    /**
     * Creates new form Recorridos
     */
    public Recorridos() {
        initComponents();
        this.setLocationRelativeTo(null);
        //this.setResizable(false);
        this.setTitle("TRANSPORTES RM DEL CARIBE S.A.S - RECORRIDOS");
        listarRecorridos();
    }
    
    public void listarRecorridos() {
        recorrido = dbRecorridos.ListarRecorridos();
        DefaultTableModel tb = (DefaultTableModel) tbRecorridos.getModel();
        for (recorridos re : recorrido) {
            tb.addRow(new Object[]{re.getId_recorrido(), re.getOrigen(), re.getDestino(), re.getKm_recorridos()});
        }
    }

    public void LimpiarRecorridos() {
        DefaultTableModel tb = (DefaultTableModel) tbRecorridos.getModel();
        for (int i = tb.getRowCount() - 1; i >= 0; i--) {
            tb.removeRow(i);
        }
    }
   
    /*
    void listarRecorridos(){
        try {
            String [] titulos={"ID","ORIGEN","DESTINO","KM_RECORRIDO"};
            String sql = "SELECT * FROM recorridos ORDER BY id_recorrido ASC";
            
            System.out.println(sql);
            model = new DefaultTableModel(null, titulos);
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/transporterm", "root", "Colombia_16");
            Statement st = cn.createStatement();
            PreparedStatement pst = cn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            String [] fila = new String[4];
            while (rs.next()) {
                fila[0] = rs.getString("id_recorrido");
                fila[1] = rs.getString("origen");
                fila[2] = rs.getString("destino");
                fila[3] = rs.getString("km_recorridos");
                model.addRow(fila);
            }
            tbRecorridos.setModel(model);
            cn.close();
            st.close();
        } catch (SQLException e) {
            System.out.println("error: "+e.getLocalizedMessage());
        }
    }
    
    public void buscarRecorrido (String texto){
        try {
            String [] titulos={"ID","ORIGEN","DESTINO","KM_RECORRIDO"};
            String filtro=""+texto+"%";
            //String sql = "SELECT * FROM recorridos WHERE origen LIKE "+'"'+filtro+'"';
            String sql = "SELECT * FROM recorridos WHERE origen LIKE '"+filtro+'"';
            System.out.println(sql);
            model = new DefaultTableModel(null, titulos);
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/transporterm", "root", "Colombia_16");
            Statement st = cn.createStatement();
            PreparedStatement pst = cn.prepareStatement(sql);
            pst.setString(1, texto);
            ResultSet rs = pst.executeQuery();
            String [] fila = new String[4];
            while (rs.next()) {
                fila[0] = rs.getString("id_recorrido");
                fila[1] = rs.getString("origen");
                fila[2] = rs.getString("destino");
                fila[3] = rs.getString("km_recorridos");
                model.addRow(fila);
            }
            tbRecorridos.setModel(model);
            cn.close();
            st.close();
        } catch (SQLException e) {
            System.out.println("error: "+e);
        }
    }
    */
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtOrigen = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDestino = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbRecorridos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("RECORRIDOS");

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("RECORRIDOS");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 10, 170, 40);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("ORIGEN");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 30, 48, 14);
        jPanel2.add(txtOrigen);
        txtOrigen.setBounds(80, 20, 150, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("DESTINO");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(250, 30, 48, 14);
        jPanel2.add(txtDestino);
        txtDestino.setBounds(310, 20, 160, 30);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 0));
        jButton2.setText("REGISTRAR");
        jPanel2.add(jButton2);
        jButton2.setBounds(20, 60, 110, 30);

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 0));
        jButton3.setText("ACTUALIZAR");
        jPanel2.add(jButton3);
        jButton3.setBounds(150, 60, 110, 30);

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 0));
        jButton4.setText("ELIMINAR");
        jPanel2.add(jButton4);
        jButton4.setBounds(280, 60, 110, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 70, 510, 100);

        tbRecorridos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "ORIGEN", "DESTINO", "KM RECORRIDOS"
            }
        ));
        jScrollPane1.setViewportView(tbRecorridos);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 190, 590, 240);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("...");
        jPanel1.add(jButton1);
        jButton1.setBounds(540, 70, 30, 23);

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(20, 50, 580, 10);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo2.jpg"))); // NOI18N
        jPanel1.add(fondo);
        fondo.setBounds(0, 0, 630, 470);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Recorridos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Recorridos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Recorridos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Recorridos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Recorridos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tbRecorridos;
    private javax.swing.JTextField txtDestino;
    private javax.swing.JTextField txtOrigen;
    // End of variables declaration//GEN-END:variables
}
